import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { getArticleById } from "../API/ArticleAPI";
import { getUserById } from "../API/ProfileAPI";
import LoadingScreen from "../components/LoadingScreen";
import toast, { Toaster } from "react-hot-toast";

// Standard fallback image
const FALLBACK_IMAGE =
  "https://placehold.co/1200x600/e2e8f0/475569?text=Article+Cover&font=montserrat";

export default function ArticleDetail() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [article, setArticle] = useState(null);
  const [authorName, setAuthorName] = useState("Unknown Author");
  const [loading, setLoading] = useState(true);
  const [imgSrc, setImgSrc] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await getArticleById(id);
        setArticle(data);
        setImgSrc(data.coverImageUrl || FALLBACK_IMAGE);

        // Fetch author info
        if (data.authorId) {
          try {
            const authorData = await getUserById(data.authorId);
            setAuthorName(
              authorData.name || authorData.username || "Unknown Author"
            );
          } catch (err) {
            console.warn("Could not fetch author details");
          }
        }
      } catch (error) {
        console.error(error);
        toast.error("Failed to load article.");
        navigate("/article");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [id, navigate]);

  if (loading) return <LoadingScreen />;
  if (!article) return null;

  return (
    <div className="min-h-screen bg-white pb-20 fredoka">
      <Toaster position="top-right" />

      {/* Hero / Cover Image */}
      <div className="w-full h-64 md:h-[400px] relative bg-gray-200">
        <img
          src={imgSrc}
          alt={article.title}
          onError={(e) => {
            e.target.onerror = null;
            setImgSrc(FALLBACK_IMAGE);
          }}
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"></div>

        <div className="absolute top-6 left-6">
          <button
            onClick={() => navigate(-1)}
            className="bg-white/20 backdrop-blur-md hover:bg-white/30 text-white px-4 py-2 rounded-full text-sm font-semibold transition-all flex items-center gap-2"
          >
            ← Back to Articles
          </button>
        </div>

        <div className="absolute bottom-0 left-0 w-full p-6 md:p-12 text-white">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-3 mb-4 text-sm font-bold uppercase tracking-wider opacity-90">
              <span className="bg-[#009e8c] px-3 py-1 rounded-full">
                Article
              </span>
              <span>•</span>
              <span>{new Date(article.publishDate).toLocaleDateString()}</span>
            </div>
            <h1 className="text-3xl md:text-5xl font-bold font-gloria leading-tight text-shadow-sm">
              {article.title}
            </h1>
          </div>
        </div>
      </div>

      {/* Article Content Container */}
      <article className="max-w-4xl mx-auto px-6 md:px-12 -mt-10 relative z-10">
        <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12 border border-gray-100">
          {/* Author Block */}
          <div className="flex items-center gap-4 mb-10 pb-8 border-b border-gray-100">
            <div className="w-12 h-12 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold text-xl uppercase">
              {authorName.charAt(0)}
            </div>
            <div>
              <p className="text-xs text-gray-400 uppercase font-bold">
                Written by
              </p>
              <p className="text-slate-800 font-bold text-lg">{authorName}</p>
            </div>
          </div>

          {/* === HTML CONTENT RENDERING === 
                Using dangerouslySetInnerHTML is necessary to display the formatting 
                (bold, italics, lists) generated by Mammoth. 
                
                We add 'prose' classes (from Tailwind Typography) to style the HTML tags automatically.
            */}
          <div
            className="prose prose-lg prose-slate max-w-none text-slate-600 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: article.content }}
          />

          {/* Footer */}
          <div className="mt-12 pt-8 border-t border-gray-100 flex flex-col md:flex-row justify-between items-center gap-6">
            <p className="text-slate-500 font-medium">Share this story:</p>
            <div className="flex gap-4">
              <button className="w-10 h-10 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center hover:bg-blue-100 transition-colors">
                f
              </button>
              <button className="w-10 h-10 rounded-full bg-sky-50 text-sky-500 flex items-center justify-center hover:bg-sky-100 transition-colors">
                t
              </button>
            </div>
          </div>
        </div>
      </article>
    </div>
  );
}
